{ lib, pkgs, config, constants, ... }:
with lib;

###########################
###### Rsync Backup #######
###########################

/*

Given a source, this module will backup that data on a regular schedule.
The output directory is based on the service name, and is mounted at nas-backup NFS share.
This was mostly generated by ChatGPT after several failed attempts.
I would not touch this much. Only fix the bare minimum if needed.

To use:

  imports = [
    ./services/rsyncBackup.nix
  ];

  services.rsyncBackup.influxdb = {
    enable = true;
    source = dataDir;
    schedule = "daily";
  };

*/

let
  backupDir = constants.nfs.dirs.backup.mountPath;
in
{
  imports = [
    ../storage/nas-backup.nix
  ];

  options.services.rsyncBackup = lib.mkOption {
    description = ''
      Configure multiple rsync backup jobs. Each backup job can be defined
      under a unique attribute name with its own settings.
    '';
    type = lib.types.attrsOf (lib.types.submodule {
      options = {
        enable = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Enable or disable this rsync backup job.";
        };

        source = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = "Path to the source directory for the backup.";
        };

        schedule = lib.mkOption {
          type = lib.types.str;
          default = "daily";
          description = "The 'OnCalendar' schedule to run the rsync backup.";
        };

        user = mkOption {
          type = types.str;
          default = "root";
          description = "[Optional] System user under which the rsync service runs.";
        };

        group = mkOption {
          type = types.str;
          default = "root";
          description = "[Optional] System group under which the rsync service runs.";
        };
      };
    });
  };

  config = let
    backups = config.services.rsyncBackup or {};
  in {
    systemd.services = lib.mapAttrs (name: jobCfg: lib.mkIf jobCfg.enable {
      name = lib.mkForce "${name}-backup.service";
      description = "Rsync backup service for ${name}";

      serviceConfig = {
        Type = "oneshot";
        # Only call -r (recursive), -l (symlinks) and --delete (remove extraneous files) flags. Others in -a (archive) flag tend to break on NFS shares.
        ExecStart = "${pkgs.rsync}/bin/rsync -rl --delete ${jobCfg.source}/ ${backupDir}/${name}/";
        User = jobCfg.user;
        Group = jobCfg.group;
        # Error 23 often indicates some partial transfer issues in rsync; we ignore it as "expected".
        SuccessExitStatus = [ 0 23 ];
      };
    }) backups;

    systemd.timers = lib.mapAttrs (name: jobCfg: lib.mkIf jobCfg.enable {
      name = lib.mkForce "${name}-backup.timer";
      description = "Rsync backup timer for ${name}";
      wants = [ "${name}-backup.service" ];
      timerConfig = {
        OnCalendar = jobCfg.schedule;
        Persistent = true;
      };
    }) backups;
  };
}