# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "xhci_pci" "ahci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  # Resolve tdarr/quicksync error https://www.reddit.com/r/jellyfin/comments/ulw3ct/comment/i87o67b/
  boot.kernelParams = [ "i915.enable_guc=2" ]; 
  boot.extraModulePackages = [ ];
  # Allow for cross-compiling Nix builds to Raspberry Pi's
  boot.binfmt.emulatedSystems = [ "aarch64-linux" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5fe4f259-2905-4733-b3a1-05d237747aed";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/326D-3C99";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3eacf5be-36ae-437c-827d-b45d21dc0b3b"; }
    ];

  # NAS Remote Drives

  fileSystems."/mnt/plex-content-unified" = 
    { device = "10.0.50.2:/mnt/janet/plex-content";
      fsType = "nfs";
    };

  fileSystems."/mnt/primary-backup" =
    { device = "10.0.50.2:/mnt/janet/backup-data/nix-nuc";
      fsType = "nfs";
    };

  fileSystems."/mnt/obsidian" =
    { device = "10.0.50.2:/mnt/eleanor/obsidian";
      fsType = "nfs";
    };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}