# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Boot Drive

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1f6191fe-8ddc-45d4-90e1-ac6452ddc544";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A7E1-04C7";
      fsType = "vfat";
    };

  # Local Drives 
  
  fileSystems."/mnt/endeavour" =
    { device = "/dev/disk/by-uuid/17ca1048-379a-44ca-8fe2-8c0ca438088e";
      fsType = "ext4";
    };

  fileSystems."/mnt/config-array" =
    { device = "/dev/disk/by-uuid/cb72b423-ac82-47ac-bb70-bed1fc458088";
      fsType = "ext4";
    };

  # NAS Remote Drives

  fileSystems."/mnt/primary-backup" = 
    { device = "10.0.50.2:/mnt/shawn/primary-backup";
      fsType = "nfs";
    };

  fileSystems."/mnt/plex-content" =
    { device = "10.0.50.2:/mnt/chidi/data";
      fsType = "nfs";
    };

  fileSystems."/mnt/plex-content-4k" = 
    { device = "10.0.50.2:/mnt/tahani/data-4k";
      fsType = "nfs";
    };


  fileSystems."/mnt/plex-content-fallback" = 
    { device = "10.0.50.2:/mnt/tahani/data";
      fsType = "nfs";
    };

  fileSystems."/mnt/plex-downloads" = 
    { device = "10.0.50.2:/mnt/downloads/plex";
      fsType = "nfs";
    };

  fileSystems."/mnt/nas-containers" = 
    { device = "10.0.50.2:/mnt/apps";
      fsType = "nfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
